# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd92a58e9bc8b1f291dc01dee1a9322f34ead016e9e8d979be801b48668869878d237a62dcd773cb37f0b0c3a26eab9509a2804591e60b9afa9a18f6fdf555ac

test:
  secret_key_base: 2637b8d37a1aec7ab8511ca7596c49e2cae0e2bcd4ef890c6efda07a5323036ef2186ec97821364f5fd027e77115b32fa033e5fbacda8e3efd1b9b758858d57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
